allowBuilds:
  rolldown: true
minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh-attachment@0.1.1-rc.2'
  - '@deepseek-ai/dsh-brand@0.1.1-rc.2'
  - '@deepseek-ai/dsh-invariants@0.1.1-rc.2'
  - '@deepseek-ai/dsh-llm@0.1.1-rc.2'
  - '@deepseek-ai/dsh-timeout@0.1.1-rc.2'
